# Generated by Django 5.2.11 on 2026-05-09 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tagging", "0003_adapt_max_tag_length"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tag",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="taggeditem",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
